name: Sync Image to Aliyun

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: likongshun@aliyun.com
        password: Test@10010
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://minio/minio:RELEASE.2022-11-17T21-20-39Z docker://registry.cn-hangzhou.aliyuncs.com/likongshun/minio:RELEASE.2022-11-17T23-20-09Z
         skopeo copy docker://postgres:15.2-alpine3.17 docker://registry.cn-hangzhou.aliyuncs.com/likongshun/postgres:15.2-alpine3.17
         skopeo copy docker://outlinewiki/outline:0.72.0-3 docker://registry.cn-hangzhou.aliyuncs.com/likongshun/outline:0.72.0-3


      # 使用 skopeo 工具将镜像同步到阿里云个人仓库中，使用时请自行源和目标修改仓库名称和镜像名称
